### PR TITLE
Adding note about worries about criticism

### LINKED ISSUE #28: Add emotional content to Code Guidelines
Probably a good idea to recognize, explicitly somewhere in Code Guidelines, that sharing code can be emotionally difficult to do if you've never done it before.

### PR DESCRIPTION
**Pull request by escowles**
@vantuyls Is this what you were thinking of?

Fixes #28

### CODE REVIEW

**Comment by mjgiarlo** [comment]
I dig it!

**Comment by mjgiarlo** [comment]
@elrayle @bess @jenlindner Have the docs here been moved to projecthydra.github.io yet, or are there plans to do so? I wonder whether we should keep updating the docs here or wait and update them in their new (?) location.

**Comment by escowles** [comment]
That's a good point @mjgiarlo — I'm happy to move these issues over there, or hold of if we're not ready yet.

**Comment by vantuyls** [comment]
@escowles Lovely, thanks.

**Pull request closed without merging**
